---
- name: Show Application & Application Service
  debug:
    msg: "Application Service {{ app_service }} belonging to {{ app }}"


- name: Get Config set for Application Service
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/config-sets?$filter=configSetName%20eq%20'{{ app_service }}'
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: json_response

- name: Get the selfLink of the Application Service
  set_fact:
    selfLink: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[0].selfLink"

- name: Move Application Service to Application defined in BIG-IQ dashboard
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/global-apps-merge-move
    method: POST
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body: |
      {
        "componentAppReferencesToMove": [
            {
              "link": "{{ selfLink }}"
            }
        ],
        "targetGlobalAppName": "{{ app }}",
        "deleteEmptyGlobalAppsWhenDone": true,
        "requireNewGlobalApp": false
      }
    body_format: json
    status_code: 200, 202
    validate_certs: false
  register: json_response
